### ISSUE TITLE
CharSet iso-8859-15, Invalid ZStream operation!

### ISSUE THREAD

**Issue by igorbastosib** [HashLoad/horse-compression#12]
I'm facing the following error while compressing a JSON string with some iso-8859-15 chars, e.g.: ü ö ä
raised exception class EZCompressionError with message 'Invalid ZStream operation!'.

Req headers:
Accept-Encoding=gzip, deflate, br
Accept-CharSet="iso-8859-15"

**Comment by viniciussanchez** [comment]
Hello @igorbastosib, did you solve the problem?

**Comment by juliomar** [comment]
Este problema não tem a ver com o Delphi e que ainda não foi liberado a correção @viniciussanchez  e @igorbastosib ?

**Comment by viniciussanchez** [comment]
Então @juliomar, eu particularmente não tive esse problema... também não uso a ISO 8859 15, teria até que fazer um teste com ela para ver o que acontece....
