### ISSUE TITLE
Estou mandando um dado para o horse, e está chegando diferente.

### ISSUE THREAD

**Issue by TalesNakasato** [HashLoad/horse-compression#14]
Boa tarde, 

Estou mandando strings com caracteres especiais para o horse (como ç, @, %,$, é, etc...), porém na hora que chega no horse, eles não estão formatados para utf-8, fazendo com que a leitura fique errada. 

Tem alguma forma de contornar esse problema?

**Comment by viniciussanchez** [comment]
Boa tarde, consegue criar uma aplicação de exemplo onde ocorra o problema? Até então não tivemos relatos disso. Ou nos passar mais informações, mais detalhes.

**Comment by viniciussanchez** [comment]
Bom dia... conseguiu resolver o problema?
