### ISSUE TITLE
Violação de acesso ao associar o Compression (Lazarus: 3.0, FPC: 3.2.2, Ubuntu: 23.10, Horse.Compression: Trunk) 

### ISSUE THREAD

**Issue by edsontmarques** [HashLoad/horse-compression#16]
Na unit Horse.Compression (Trunk do Repositório no Github), linha 31 temos a seguinte instrução:

`Result := {$IF DEFINED(FPC)}@Middleware{$ELSE}Middleware{$ENDIF};`

Neste caso, está ocorrendo, aqui comigo, uma violação de acesso. Creio que seja porque a unidade está configurada para a compilação em MODE DELPHI e, por isso, não seria necessário fazer a verificação do tipo de compilador e nem deveríamos usar o "@".

`Result := Middleware;`

**Comment by viniciussanchez** [comment]
Bug fix: https://github.com/HashLoad/horse-compression/commit/250fa0f4394d663345c1c5b222f3b22d245b5f2e
