### ISSUE TITLE
Item not found

### ISSUE THREAD

**Issue by CRibeiro1072** [HashLoad/horse-compression#8]
Olá Vinicios, boa tarde, tudo bem por ai? Espero que sim. Sou Claudinei e fico feliz por ter pessoas com você que contribui enormemente com a comunidade Delphi, sou autodidata e estou trabalho em um projeto usado Horse, Dataset Serialize e Horse Compression e me deparei com o seguinte cenário, quando faço a instalção via boss o mesmo funciona corretamente, mas quando baixo e faço a instalação dos componentes manualmente, o mesmo me reporta o seguinte erro; Raised exception class EListError with message "Item not found". Fazendo o debug da aplicação constatei que quando entra no procedimento Middleware na unidade de código Horse.Compression o parametro passado para a constante ACCEPT_ENCONDIG está em caixa baixa e ele chega com as iniciais em caixa alta na lista dentro do headers da requisição, feito essa correção a aplicação funcionou normalmente. OBS: Acredito que esse erro se deve ao fato das adições das units Horse.Core.Param.Header.pas, Horse.Provider.IOHandleSSL.pas e Horse.Rtti.pas no projeto Horse, pois as mesmas não se encontram na pasta src quando se instala via boss. Sem mais agradeço a você e a todos que se empenham em ajudar a comunidade.
![Debug](https://user-images.githubusercontent.com/51350550/142741614-10da3d60-1219-4110-ae67-f7e25435efe7.png)
![Postman](https://user-images.githubusercontent.com/51350550/142741615-5a19177d-4465-4384-afd2-4a5014827627.png)
![Correção](https://user-images.githubusercontent.com/51350550/142741613-2f9db85f-e4e5-4bc2-8da3-e2520cdae56b.png)

**Comment by viniciussanchez** [comment]
Bom dia... obrigado por reportar o erro. Sim estamos trabalhando no Horse, por isso sempre aconselhamos a utilizar o Boss para realizar a instalação ou então, se for fazer de forma manual, sempre baixar o código fonte das releases liberadas, e nunca o código atual pois pode conter erros como o apresentado....

**Comment by CRibeiro1072** [comment]
Boa noite. Obrigado pelo retorno.

Em seg., 22 de nov. de 2021 às 08:17, Vinicius Sanchez <
***@***.***> escreveu:
